{
 "title": "Bluefors parameters",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Bluefors",
    "query": "BF1 : 10.1.71.127:9101, BF2 : 10.1.71.128:9101"
   }
  ]
 },
 "panels": [
  { "title": "Control unit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mixture handling system",
   "type": "canvas",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "bluefors_mixture_valve_state{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bluefors_mixture_turbo_state{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bluefors_mixture_scroll_state{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bluefors_mixture_compressor_state{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bluefors_mixture_flow_moles_per_second{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "bluefors_mixture_pressure_bars{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scroll1 frequency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_scroll_compressor_rotational_frequency_hertz{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT1",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", flange=\"pt1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MXC",
   "type": "stat",
   "gridPos": { "h": 18, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", flange=\"mxc\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Turbo1 frequency",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_turbo_compressor_active_rotational_speed_hertz{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PT2",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", flange=\"pt2\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pulse tube oil temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_pulse_tube_compressor_oil_temperature_celsius{instance=\"$Bluefors\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STILL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", flange=\"still\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Flange temperature logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Flange temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "{{flange}}"
    }
   ]
  },
  {
   "title": "Sample temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "kelvin" } },
   "targets": [
    {
     "expr": "bluefors_flanges_temperature_kelvins{instance=\"$Bluefors\", job=\"bluefors_exporter\", flange=\"mxc\"}",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "title": "Mixture handling system logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "pressurebar" } },
     "targets": [
      {
       "expr": "bluefors_mixture_pressure_bars{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "{{sensor}}"
      }
     ]
    },
    {
     "title": "Flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "mmol/s" } },
     "targets": [
      {
       "expr": "bluefors_mixture_flow_millimoles_per_second{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "Flow"
      },
      {
       "expr": "bluefors_mixture_flow_moles_per_second{instance=\"$Bluefors\", job=\"bluefors_exporter\"} * 1000",
       "legendFormat": "Flow"
      }
     ]
    }
   ]
  },
  {
   "title": "Control unit logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scroll",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "bluefors_mixture_scroll_state{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "{{scroll}}"
      }
     ]
    },
    {
     "title": "Valves",
     "type": "state-timeline",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "bluefors_mixture_valve_state{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "{{valve}}"
      }
     ]
    },
    {
     "title": "Turbo",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "bluefors_mixture_turbo_state{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "{{turbo}}"
      }
     ]
    },
    {
     "title": "Heat switch",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "bluefors_control_unit_heat_switch_state{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "{{heat_switch}}"
      }
     ]
    },
    {
     "title": "Pulse tube compressor",
     "type": "state-timeline",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "bluefors_control_unit_pulse_tube_state{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "State"
      }
     ]
    }
   ]
  },
  { "title": "Pulse Tube compressor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "bluefors_pulse_tube_compressor_helium_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Helium"
    },
    {
     "expr": "bluefors_pulse_tube_compressor_oil_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Oil"
    },
    {
     "expr": "bluefors_pulse_tube_compressor_coolant_in_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Coolant In"
    },
    {
     "expr": "bluefors_pulse_tube_compressor_coolant_out_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Coolant Out"
    }
   ]
  },
  {
   "title": "Helium pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "bluefors_pulse_tube_compressor_high_pressure_bars{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "High"
    },
    {
     "expr": "bluefors_pulse_tube_compressor_low_pressure_bars{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Low"
    }
   ]
  },
  {
   "title": "Motor current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "bluefors_pulse_tube_compressor_motor_current_amperes{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Scroll 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "bluefors_scroll_compressor_controller_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "Controller"
      },
      {
       "expr": "bluefors_scroll_compressor_pump_temperature_celsius{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "Pump"
      }
     ]
    },
    {
     "title": "Rotational speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "bluefors_scroll_compressor_rotational_frequency_hertz{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Turbo 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "bluefors_turbo_compressor_drive_power_watt{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Rotational speed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "rothz" } },
     "targets": [
      {
       "expr": "bluefors_turbo_compressor_active_rotational_speed_hertz{instance=\"$Bluefors\", job=\"bluefors_exporter\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}